[project]
name = "data-cleaner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8,<3.13"
dependencies = [ 
    "pandas",
    "openpyxl"
    ]

[tool.poetry]
packages = []

package-mode = false
